source 'ssh://ioscoder@192.168.1.29:29418/core/ios/cocopodsSpec'

platform :ios, '9.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
